site_name: Brickman Lab
repo_url: https://github.com/brickmanlab/wiki
repo_name: brickmanlab/wiki

# nav:
#  - index.md
#  - nextflow_tower.md

theme:
  name: material
  logo: BrickmanLab.jpeg
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables

plugins:
  - search
  - table-reader
  - git-revision-date-localized:
      enable_creation_date: true
